blog/urls.py
# -*- coding:utf-8 -*-
# @FileName  :urls.py.py
# @Time      :2025/3/27 16:32
# @Author    :wsk
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("blog/<int:blog_id>/", views.blog_detail, name="blog_detail"),
    path("blog/pub/", views.pub_blog, name="pub_blog"),
    path("blog/submit_comment/", views.submit_comment, name="submit_comment"),
    path("search/", views.search, name="search"),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("myauth/", include("myauth.urls")),
]

myauth/urls.py
# -*- coding:utf-8 -*-
# @FileName  :urls.py
# @Time      :2025/3/27 19:10
# @Author    :wsk

from django.urls import path
from . import views

app_name = "myauth"

urlpatterns = [
    path("sign_in/", views.sign_in, name="sign_in"),
    path("log_out/", views.log_out, name="log_out"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("captcha/", views.send_email_captcha, name="send_email_captcha"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <div class="d-flex align-items-center mb-2 mb-lg-0 me-4">
                <img src="{% static 'images/wifi-off.svg' %}" alt="logo" height="40">
            </div>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'blog:index' %}" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-secondary">发布博客</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="GET">
                <input name="keyword" type="search" class="form-control" placeholder="Search..." aria-label="Search">
            </form>
            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'images/avatar.webp' %}" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'myauth:log_out' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'myauth:sign_in' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'myauth:sign_up' %}" type="button" class="btn btn-primary">注册</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    {% block main %}{% endblock %}
</main>

<!-- Bootstrap Bundle with Popper -->
<script src="{% static 'bootstrap5/popper.min.js' %}"></script>
<script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}博客详情{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}

{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'images/avatar.webp' %}" alt="" height="28" width="28" class="rounded-circle">
        <span class="ms-2">{{ blog.author.username }} </span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.pub_time }} </span>发布
    </div>
    <hr>
    <div class="mt-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div>
        <h3>评论({{ blog.comments.all|length }})</h3>
        <form action="{% url 'blog:submit_comment' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div>
                <input type="text" class="form-control" placeholder="请输入..." name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">
                    提交
                </button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item mb-3">
                    <div class="d-flex justify-content-between text-body-secondary">
                        <div class="user-info">
                            <img src="{% static 'images/avatar.webp' %}" height="30" width="30" alt=""
                                 class="rounded-circle">
                            <span class="ms-2">{{ comment.author.username }}</span>
                        </div>
                        <div>{{ comment.pub_time }}</div>
                    </div>
                    <span class="mt-2">{{ comment.content }}</span>
                </li>
            {% endfor %}

        </ul>
    </div>
    <script>
        hljs.highlightAll();
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}首页{% endblock %}

{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-3">
    {% for blog in blogs %}
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height: 100px">
                    <p class="card-text">{{ blog.content|striptags|truncatechars:200 }}</p>
                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'images/avatar.webp' %}" alt="avatar" class="rounded-circle" width="28"
                             height="28">
                        {{ blog.author.username }}
                    </div>
                    <div>{{ blog.pub_time}}</div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/pub_blog.html
{% extends 'base.html' %}
{% load static %}

{% block title %}发布博客{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}

{% block main %}
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">标题</label>
                <input type="text" class="form-control" name="title" placeholder="请输入标题">
            </div>

            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select" id="category-list">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label class="form-label">内容</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" id="submit-btn">提交</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/sign_in.html
{% extends 'base.html' %}
{% load static %}

{% block title %}登录{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1 class="h3 mb-3 fw-normal text-center">登录</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% if error %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
            {% endif %}
            <div class="mb-3">
                <div class="mb-3">
                    <label>邮箱</label>
                    <input type="email" name="email" class="form-control" placeholder="邮箱" required autofocus>
                </div>
                <div class="mt-3">
                    <label>密码</label>
                    <input type="password" name="pwd" class="form-control" placeholder="密码" required autofocus>
                </div>
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    记住我
                </label>
            </div>
            <div class="mb-3">
                <button class="btn btn-lg btn-primary w-100" type="submit">登录</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/sign_up.html
{% extends 'base.html' %}
{% load static %}

{% block title %}注册{% endblock %}
{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src={% static 'js/sign_up.js' %}></script>
{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1 class="h3 mb-3 fw-normal text-center">注册</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <div class="mb-3">
                    <label>用户名</label>
                    <input type="text" name="username" class="form-control" placeholder="用户名" required autofocus>
                </div>
                <div class="mb-3">
                    <label>邮箱</label>
                    <input type="email" name="email" class="form-control" placeholder="邮箱" required autofocus>
                </div>
                <div class="mb-3 input-group">
                    <label>验证码</label>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="验证码"
                               aria-label="captcha" aria-describedby="button-addon2" name="captcha">
                        <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                    </div>
                </div>
                <div class="mt-3">
                    <label>密码</label>
                    <input type="password" name="pwd" class="form-control" placeholder="密码" required autofocus>
                </div>
            </div>

            <div class="mb-3">
                <button class="btn btn-lg btn-primary w-100" type="submit">注册</button>
            </div>
        </form>
    </div>
{% endblock %}